### ISSUE TITLE
tutorial data file

### ISSUE THREAD

**Issue by shuxiaoxiaoshu** [quon-titative-biology/siVAE#1]
Hi, nice work. Would you post the preprocessed file "sample_fetal_liver_atlas_dataset.h5ad" so that we can try the tutorial as in the page (https://github.com/quon-titative-biology/siVAE/blob/master/tutorial/tutorial.md)?

**Comment by yonchoi** [comment]
Hi, the previous dataset was too large to fit into the repository, so I've uploaded a smaller version. Thank you for pointing this out.
